paths:
  output_root: "./outputs"

# --- 模型特定配置区 ---

# 1. Gemini 配置块
nanobanana1_model:
  base_url: "http://123.129.219.111:3000"
  api_key: "sk-WmVE6CJl6GrhT5MjjlN4Jl2yg3J9Pp1OAvKHqIbQhHCChWdJ"
  generation_model_name: "gemini-2.5-flash-image-preview"
  understanding_model_name: "gemini-2.5-flash"

nanobanana2_model:
  base_url: "http://123.129.219.111:3000"
  api_key: "sk-WmVE6CJl6GrhT5MjjlN4Jl2yg3J9Pp1OAvKHqIbQhHCChWdJ"
  generation_model_name: "gemini-3-pro-image-preview"
  understanding_model_name: "gemini-3-pro"

# 2. (未来扩展) SDXL 配置块
sdxl_model:
  api_url: "http://localhost:7860"
  steps: 30